# Generated by Django 2.1.4 on 2018-12-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181217_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_unit',
            name='link',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='gallery_unit',
            name='description',
            field=models.TextField(),
        ),
    ]
