# Generated by Django 2.1.4 on 2018-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20181217_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_unit',
            name='link',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
