# Generated by Django 2.1.4 on 2018-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20181217_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_unit',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
